### PR TITLE
add warning text for open data inventory upload page

### PR DESCRIPTION
**Pull request by fanjinfei**

### CODE REVIEW

**Comment by fanjinfei** [comment]
@wardi ready for review

**Comment by wardi** [comment]
You can use `{{ super() }}` to insert the previously-defined block content into a block, that's a lot better than copying it.

Is there a reason you can't use `upload_info` like ati, travelq and hospitalityq do?

**Comment by fanjinfei** [comment]
I did change the html5 validation message for French.

**Comment by wardi** [comment]
The language fix that would be better in recombinant

**Comment by fanjinfei** [comment]
The tickets is asking to put the text on top of the submit button and using warning style, otherwise we can use upload_info.

**Pull request merged**
