### PR TITLE
OPEN-2353: Update the Similar Records section of the Package read tem…

### PR DESCRIPTION
**Pull request by thriuin**
…plate to use Search v.2

### CODE REVIEW

**Comment by wardi** [comment]
If the settings aren't defined we'll get an error rendering the page, want to add the production urls as defaults to the `get` calls?

**Comment by wardi** [comment]
oh, not an error, just a broken url with "None" in it

**Comment by thriuin** [comment]
Oops, already pulled the trigger on  this. If the setting is not defined, I thought the test on line 233 would prevent the block from rendering. If that isn't the case, we could add production as a default.

**Comment by wardi** [comment]
233 will always be true because a string is always returned from the helper (it would start with "None/..." if the appropriate setting isn't defined)

This makes me wonder about the best way to manage multilingual urls for external services. We could use gettext on them like other things instead of if/else in the code. Still need multiple settings in the ini file for different domains though.

If we follow your lead on multilingual urls in the ckan portion of the site I can see making the `url_for` logic in ckan language-aware and provide a bunch of "translations" for url components and have them automatically registered as alternate urls. That way most of ckan would just work for multilingual links and redirects, and it would even be possible to customize core urls with translations instead of code overriding.

**Comment by thriuin** [comment]
Ah, looking more closely at it now, I realize this won't work. For now, a default to the portal is probably best. I could also extend Search to provide a meaningful message when the UUID can't be found in Solr. Right now it will just return an empty list.
I definitely like your idea for translations for the urls. That definitely seems like a better long-term approach than hard-coding EN and FR toggles. Having different domains is an irritating complication however - I think there is a reason you don't see it very often.

**Pull request merged**
