### PR TITLE
Added save_button_text block override to the new package form interna…

### PR DESCRIPTION
**Pull request by JVickery-TBS**
…l template.

### CODE REVIEW

**Comment by wardi** [comment]
isn't this the same as the block it's overriding?

**Comment by JVickery-TBS** [comment]
@wardi It is overriding this block https://github.com/open-data/ckan/blob/canada-v2.8/ckan/templates/package/snippets/package_form.html#L43

From what I could tell from debugging, if the template exists in the ckanext directory, it will load that one and not the one in the ckan core install. So it seem that `ckanext-canada/ckanext/canada/templates/internal/package/new_package_form.html` is loaded, not `ckan/ckan/templates/package/new_package_form.html`

**Comment by wardi** [comment]
could the problem be that line 1 is extending the wrong template and we should use `{% ckan_extends %}` instead of `{% extends 'package/snippets/package_form.html' %}`

**Comment by wardi** [comment]
or even better can we fix the problem by deleting this template? I don't see the point of the only other block override here

**Comment by JVickery-TBS** [comment]
@wardi Template is deleted and works fine locally.

**Comment by wardi** [comment]
LGTM

**Pull request merged**
