### PR TITLE
OPN-55 changing style of resource format tags

### PR DESCRIPTION
**Pull request by HoussamBedja**

### CODE REVIEW

**Comment by wardi** [comment]
this looks the same as the block in `canada/templates/public/snippets/package_item.html` or am I missing something?

**Comment by HoussamBedja** [comment]
Yes but it seems like you (or whoever wrote the code before) did a super.super() to skip `canada/templates/public/snippets/package_item.html` in order to "strip the map cart buttons". But you lost the styling by skipping that file. 

Another way of doing this could be by not skipping the file with super.super(), and instead wrapping the 'add to map cart' logic in a new block, which will be set to being an empty block in `internal/admin/snippets/package_item.html`

**Comment by wardi** [comment]
I mean we could change that line to `{{ super() }}` to avoid copying a bunch of code because the fgp flag would never be set on registry datasets

**Comment by HoussamBedja** [comment]
Oh okay, the original code had a "strip map cart buttons" comment so I assumed it was being affected even on registry. Will apply those changes then.

**Pull request merged**
