### PR TITLE
Space Before Colons for French

### PR DESCRIPTION
**Pull request by JVickery-TBS**
- Space before colons for inline colons in templates.

### CODE REVIEW

**Review by wardi — APPROVED** [review]
This works but I'm sure this isn't the recommended way to localize colons :thinking:

**Comment by JVickery-TBS** [comment]
Mmmm good point, not sure why I did not just move the colons into the `gettext`s. Will do that and update catalogues.

**Comment by wardi** [comment]
I'm sure there are cases where we want the same string translated and used as a label in some cases but not in others. Just wondering if there's something like the date/number formatting stuff built in to babel that covers colon spacing or something.

Having two versions of all the strings that might have a following colon doesn't seem like a great solution either

**Comment by JVickery-TBS** [comment]
Yeah after looking online for quite some time, there does not really seem to be a way to localize punctuation like this in a perfect way. Either have two strings in PO file or do the dynamic thing I am doing here. Or just choose to use no colon/punctuation.

So I think we can just put the colons in the PO files and be "normal" in that way.

**Pull request merged**
