### PR TITLE
More WebForm Tests

### PR DESCRIPTION
**Pull request by JVickery-TBS**
Adding tests for new user form.

Adding tests for all of the Recombinant related UI and forms.

### CODE REVIEW

**Comment by JVickery-TBS** [comment]
@wardi I have some placeholder test methods in there now for the Recombinant test class. I think those should be all the ones we need?

But my main question is if we need those tests for each PD type? As the create single record and the validation tests would be different for each PD type? That way we would test to make sure that all of our table/schema stuff for the PD types are correct?

Let me know if you think we should have these tests for each PD type. I could try abstracting the class to subclass it for each PD type.

**Comment by wardi** [comment]
There's no need to abstract pd tests. Better to keep them as simple (and repetitive) as possible or we'll have to start writing tests for our tests.

**Comment by wardi** [comment]
Having tests of the forms for one PD type is sufficient because we have API tests for all the types that should cover all the specific validation rules.

**Comment by JVickery-TBS** [comment]
@wardi okay all of these tests should be good now. These should now cover the user registration UI and the PD UIs (per role type depending on the test e.g. bulk-delete and xls_upload).

**Comment by wardi** [comment]
Looks great @JVickery-TBS really happy to have some coverage on this functionality

**Pull request merged**
